In [0]:
def compute_cost(X, y, thetas):
  m = X.shape[0]
  y_hat = np.dot(X, thetas)
  sse = np.sum((y_hat - y)**2)
  cost = sse / (2*m)
  return cost

def gradient_descent(X, y, alpha=0.01, num_iters=1500):
  thetas = np.array([0, 0]).reshape(-1, 1)
  m = X.shape[0]
  J_history = np.zeros(num_iters)
    
  for num_iter in range(num_iters):
    h = np.dot(X, thetas)
    loss = h - y
    gradient = np.dot(X.T, loss) / m
    thetas = thetas - alpha * gradient
    cost = compute_cost(X, y, thetas=thetas)
    J_history[num_iter] = cost

  return thetas, J_history

In [0]:
import pandas as pd
#from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt

train_url = "https://storage.googleapis.com/kaggle_datasets/House-Prices-Advanced-Regression-Techniques/train.csv"
test_url = "https://storage.googleapis.com/kaggle_datasets/House-Prices-Advanced-Regression-Techniques/test.csv"
labeled = pd.read_csv(train_url)
test = pd.read_csv(test_url)
print(labeled.shape)
print(test.shape)

#labeled.dtypes
labeled[['OverallQual']] =labeled[['OverallQual']].astype(float)

(1460, 81)
(1459, 80)

In [0]:
labeled.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [0]:
test.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal

In [0]:
import numpy as np

row_indice = np.array(labeled.index)
np.random.shuffle(row_indice)
row_indice

array([ 312,  957,  354, ..., 1100, 1236,  549])

In [0]:
labeled_shuffle = labeled.loc[row_indice, :]
labeled_shuffle

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
312,313,190,RM,65.0,7800,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,5,2006,WD,Normal,119900
957,958,20,RL,70.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2007,WD,Normal,132000
354,355,50,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,140000
256,257,60,FV,64.0,8791,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,207500
657,658,70,RL,60.0,7200,Pave,NaN,Reg,HLS,AllPub,...,0,NaN,MnPrv,NaN,0,2,2008,WD,Normal,149000
611,612,80,RL,NaN,10395,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,500,7,2007,WD,Normal,148000
296,297,50,RM,75.0,13710,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,152000
931,932,20,RL,70.0,9100,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,7,2009,WD,Normal,117500
1278,1279,60,RL,75.0,9473,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2008,WD,Normal,237000
647,648,20,RL,85.0,10452,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,155000
348,349,160,RL,36.0,2448,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2008,WD,Normal,154000
65,66,60,RL,76.0,9591,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2007,WD,Normal,317000
346,347,20,RL,NaN,12772,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Gar2,15500,4,2007,WD,Normal,151500
436,437,50,RM,40.0,4400,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,10,2006,WD,Normal,116000
124,125,20,RL,48.0,17043,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2009,WD,Normal,181000
557,558,50,C (all),60.0,11040,Pave,NaN,Reg,Low,AllPub,...,0,NaN,NaN,NaN,0,9,2006,COD,Normal,108000
1439,1440,60,RL,80.0,11584,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2007,WD,Normal,197000
663,664,85,RL,90.0,10012,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,4,2008,WD,Normal,137500
625,626,20,RL,87.0,10000,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,160000
1277,1278,80,RL,NaN,17871,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,197900
1161,1162,20,RL,NaN,14778,Pave,NaN,IR1,Low,AllPub,...,0,NaN,NaN,NaN,0,11,2008,WD,Normal,224000
763,764,60,RL,82.0,9430,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,WD,Normal,337000
1329,1330,60,RL,63.0,9084,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,176500
588,589,20,RL,65.0,25095,Pave,NaN,IR1,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Partial,143000
1364,1365,160,FV,30.0,3180,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml,144152
1260,1261,60,RL,NaN,24682,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,181000
1211,1212,50,RL,152.0,12134,Pave,NaN,IR1,Bnk,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,164000
854,855,20,RL,102.0,17920,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,170000
1328,1329,50,RM,60.0,10440,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,1150,6,2008,WD,Normal,256000
1119,1120,20,RL,70.0,7560,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdWo,NaN,0,7,2006,WD,Normal,133700
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
281,282,20,FV,60.0,7200,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2006,New,Partial,185000
1112,1113,20,RL,73.0,7100,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,129900
913,914,90,RH,82.0,6270,Pave,NaN,Reg,HLS,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,145000
307,308,50,RM,NaN,7920,Pave,Grvl,IR1,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,3,2008,WD,Normal,89500
809,810,75,RM,90.0,8100,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,11,2009,WD,Normal,106000
1287,1288,20,RL,NaN,36500,Pave,NaN,IR1,Low,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,190000
875,876,60,FV,75.0,9000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,New,Partial,303477
434,435,180,RM,21.0,1890,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,81000
1067,1068,60,RL,80.0,9760,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,167900
301,302,60,RL,66.0,16226,Pave,NaN,IR3,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,267000
1070,1071,20,RL,72.0,10152,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2007,WD,Normal,135000
266,267,60,RL,70.0,11207,Pave,NaN,IR1,HLS,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,185000
1136,1137,50,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,119000
1378,1379,160,RM,21.0,1953,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2006,WD,Normal,83000
1317,1318,120,FV,47.0,4230,Pave,Pave,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2007,New,Partial,208900
175,176,20,RL,84.0,12615,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,6,2007,WD,Normal,243000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
188,189,90,RL,64.0,7018,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Alloca,153337
538,539,20,RL,NaN,11553,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,158000
542,543,20,RL,78.0,10140,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2009,WD,Normal,213250
447,448,60,RL,NaN,11214,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,199900
791,792,80,RL,NaN,11333,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,146800
835,836,20,RL,60.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2010,WD,Normal,128000
923,924,120,RL,50.0,8012,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,193000
299,300,20,RL,80.0,14000,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,NaN,0,8,2009,WD,Family,158500
505,506,90,RM,60.0,7596,Pave,Grvl,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2009,COD,Normal,124500
83,84,20,RL,80.0,8892,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2007,COD,Normal,126500
1100,1101,30,RL,60.0,8400,Pave,NaN,Reg,Bnk,AllPub,...,0,NaN,NaN,NaN,0,1,2009,WD,Normal,60000
1236,1237,160,RL,36.0,2628,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2010,WD,Normal,175500
549,550,60,FV,75.0,9375,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,11,2009,WD,Normal,263000

In [0]:
#Dataset Split

m = labeled.shape[0]
train_threshold = int(m * 0.7)
train = labeled.iloc[:train_threshold, :]
validation = labeled.iloc[train_threshold:, :]
print(train.shape)
print(validation.shape)
train.head (10)

(1021, 81)
(439, 81)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.0,14115,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.0,10084,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,NaN,10382,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
8,9,50,RM,51.0,6120,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2008,WD,Abnorml,129900
9,10,190,RL,50.0,7420,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,1,2008,WD,Normal,118000

In [0]:
# Find out missing ratio

ntrain = train.shape[0]
ntest = test.shape[0]
y_train = train.SalePrice.values
all_data = pd.concat((train, test)).reset_index(drop=True)
all_data.drop(['SalePrice'], axis=1, inplace=True)
print("all_data size is : {}".format(all_data.shape))

all_data_na = (all_data.isnull().sum() / len(all_data)) * 100
all_data_na = all_data_na.drop(all_data_na[all_data_na == 0].index).sort_values(ascending=False)[:30]
missing_data = pd.DataFrame({'Missing Ratio' :all_data_na})
missing_data.head(20)

all_data size is : (2480, 80)

              Missing Ratio
PoolQC            99.798387
MiscFeature       96.209677
Alley             93.064516
Fence             80.483871
FireplaceQu       49.112903
LotFrontage       16.290323
GarageQual         5.483871
GarageCond         5.483871
GarageFinish       5.483871
GarageYrBlt        5.483871
GarageType         5.403226
BsmtExposure       2.862903
BsmtCond           2.862903
BsmtQual           2.822581
BsmtFinType2       2.782258
BsmtFinType1       2.741935
MasVnrType         0.887097
MasVnrArea         0.846774
MSZoning           0.161290
BsmtFullBath       0.080645

In [0]:
# Clean NaN

from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
from scipy import stats
from scipy.stats import norm, skew



train["PoolQC"] = train["PoolQC"].fillna("None")
train["MiscFeature"] = train["MiscFeature"].fillna("None")
train["Alley"] = train["Alley"].fillna("None")
train["Fence"] = train["Fence"].fillna("None")
train ["FireplaceQu"] = train ["FireplaceQu"].fillna("None")
train ["LotFrontage"] = train.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    train [col] = train [col].fillna('None')
for col in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    train[col] = train[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    train[col] = train[col].fillna(0)
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    train [col] = train [col].fillna('None')
train["MasVnrType"] = train["MasVnrType"].fillna("None")
train["MasVnrArea"] = train["MasVnrArea"].fillna(0)
train ['MSZoning'] = train['MSZoning'].fillna(train['MSZoning'].mode()[0])

#train = train.drop(columns=['Utilities'])

train ["Functional"] = train ["Functional"].fillna("Typ")
train ['Electrical'] = train ['Electrical'].fillna(train['Electrical'].mode()[0])
train ['KitchenQual'] = train ['KitchenQual'].fillna(train ['KitchenQual'].mode()[0])
train ['Exterior1st'] = train ['Exterior1st'].fillna(train['Exterior1st'].mode()[0])
train['Exterior2nd'] = train['Exterior2nd'].fillna(train['Exterior2nd'].mode()[0])
train['SaleType'] = train['SaleType'].fillna(train['SaleType'].mode()[0])
train ['MSSubClass'] = train ['MSSubClass'].apply(str)
train ['YrSold'] = train ['YrSold'].astype(str) #can change to year left
train ['MoSold'] = train ['MoSold'].astype(str)
train['TotalSF'] = train['TotalBsmtSF'] + train['1stFlrSF'] + train['2ndFlrSF']

# #Find Categorical Variables

# cols = train.columns
# num_cols =train._get_numeric_data().columns
# cols = list(set(cols) - set(num_cols))
# print (num_cols)

#Find out skewed features 
numeric_feats = train.dtypes[train.dtypes != "object"].index
skewed_feats = train[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})
skewness.head(10)
#Box Cox Transformation of skewed features

skewness = skewness[abs(skewness.Skew) > 0.75]
print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))
from scipy.special import boxcox1p
skewed_features = skewness.index
lam = 0.15

for feat in skewed_features:
    train[feat] += 1
    if feat != 'SalePrice':
        train[feat] = boxcox1p(train[feat], lam)
    else :
        train ['SalePriceSkewed'] = boxcox1p(train[feat], lam)
        

        

train.head()

#labelencoding


#from sklearn.preprocessing import LabelEncoder
cols = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'PoolQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional', 'Fence', 'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street', 'Alley', 'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold','SaleCondition','SaleType','LandContour','Utilities','Fence','MiscFeature')




#process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(train[c].values)) 
    train[c] = lbl.transform(list(train[c].values))

#shape        
print('Shape all_data: {}'.format(train.shape))
train.head()

#onehot

train = pd.get_dummies(train)
train

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:32: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:38: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:64: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:66: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

Skew in numerical features:

There are 22 skewed numerical features to Box Cox transform

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:68: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

NameError: ignored

In [0]:
# #Find out skewed features 
# numeric_feats = train.dtypes[train.dtypes != "object"].index
# skewed_feats = train[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
# print("\nSkew in numerical features: \n")
# skewness = pd.DataFrame({'Skew' :skewed_feats})
# skewness.head(10)
# #Box Cox Transformation of skewed features

# skewness = skewness[abs(skewness.Skew) > 0.75]
# print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))
# from scipy.special import boxcox1p
# skewed_features = skewness.index
# lam = 0.15

# for feat in skewed_features:
#     train[feat] += 1
#     if feat != 'SalePrice':
#         train[feat] = boxcox1p(train[feat], lam)
#     else :
#         train ['SalePriceSkewed'] = boxcox1p(train[feat], lam)
        

        

# train.head()

In [0]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Imputer
from scipy import stats
from scipy.stats import norm, skew

validation["PoolQC"] = validation["PoolQC"].fillna("None")
validation["MiscFeature"] = validation["MiscFeature"].fillna("None")
validation["Alley"] = validation["Alley"].fillna("None")
validation["Fence"] = validation["Fence"].fillna("None")
validation ["FireplaceQu"] = validation ["FireplaceQu"].fillna("None")
validation ["LotFrontage"] = validation.groupby("Neighborhood")["LotFrontage"].transform(
    lambda x: x.fillna(x.median()))
for col in ('GarageType', 'GarageFinish', 'GarageQual', 'GarageCond'):
    validation [col] = validation [col].fillna('None')
for col in ('GarageYrBlt', 'GarageArea', 'GarageCars'):
    validation[col] = validation[col].fillna(0)
for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF','TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath'):
    validation[col] = validation[col].fillna(0)
for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):
    validation [col] = validation [col].fillna('None')
validation["MasVnrType"] = validation["MasVnrType"].fillna("None")
validation["MasVnrArea"] = validation["MasVnrArea"].fillna(0)
validation ['MSZoning'] = validation['MSZoning'].fillna(validation['MSZoning'].mode()[0])

#validation = validation.drop(columns=['Utilities'])

validation ["Functional"] = validation ["Functional"].fillna("Typ")
validation ['Electrical'] = validation ['Electrical'].fillna(validation['Electrical'].mode()[0])
validation ['KitchenQual'] = validation ['KitchenQual'].fillna(validation ['KitchenQual'].mode()[0])
validation ['Exterior1st'] = validation ['Exterior1st'].fillna(validation['Exterior1st'].mode()[0])
validation['Exterior2nd'] = validation['Exterior2nd'].fillna(validation['Exterior2nd'].mode()[0])
validation['SaleType'] = validation['SaleType'].fillna(validation['SaleType'].mode()[0])
validation ['MSSubClass'] = validation ['MSSubClass'].apply(str)
validation ['YrSold'] = validation ['YrSold'].astype(str) #can change to year left
validation ['MoSold'] = validation ['MoSold'].astype(str)
validation['TotalSF'] = validation['TotalBsmtSF'] + validation['1stFlrSF'] + validation['2ndFlrSF']

#skew
numeric_feats = validation.dtypes[validation.dtypes != "object"].index
skewed_feats = validation[numeric_feats].apply(lambda x: skew(x.dropna())).sort_values(ascending=False)
print("\nSkew in numerical features: \n")
skewness = pd.DataFrame({'Skew' :skewed_feats})
skewness.head(10)

#Box Cox Transformation skewed features

skewness = skewness[abs(skewness.Skew) > 0.75]
print("There are {} skewed numerical features to Box Cox transform".format(skewness.shape[0]))
from scipy.special import boxcox1p
skewed_features = skewness.index
lam = 0.15
for feat in skewed_features:
    validation [feat] += 1
    if feat != 'SalePrice':
        validation[feat] = boxcox1p(validation[feat], lam)
    else :
        validation ['SalePriceSkewed'] = boxcox1p(validation[feat], lam) 
#labelencoding

from sklearn.preprocessing import LabelEncoder
cols = ('FireplaceQu', 'BsmtQual', 'BsmtCond', 'GarageQual', 'GarageCond', 
        'ExterQual', 'ExterCond','HeatingQC', 'PoolQC', 'KitchenQual', 'BsmtFinType1', 
        'BsmtFinType2', 'Functional', 'Fence', 'BsmtExposure', 'GarageFinish', 'LandSlope',
        'LotShape', 'PavedDrive', 'Street', 'Alley', 'CentralAir', 'MSSubClass', 'OverallCond', 
        'YrSold', 'MoSold')
#process columns, apply LabelEncoder to categorical features
for c in cols:
    lbl = LabelEncoder() 
    lbl.fit(list(validation[c].values)) 
    validation[c] = lbl.transform(list(validation[c].values))

#shape        
print('Shape all_data: {}'.format(validation.shape))


print(validation.head())

***italicized text***

```
# This is formatted as code
```

In [0]:
# Find out correlation
train.corr()
saleprice_corr = train.corr()["SalePrice"]
saleprice_corr.abs().nlargest(25)

In [0]:
# from sklearn.linear_model import LinearRegression
# from sklearn.metrics import mean_squared_error
# from sklearn.metrics import mean_squared_log_error
# reg = LinearRegression()
# X_train = train["YearBuilt"].values.reshape(-1, 1)
# y_train = train.loc[:, "SalePrice"].values.reshape(-1, 1)
# reg.fit(X_train, y_train)
# y_hat = reg.predict(validation["YearBuilt"].values.reshape(-1, 1))
# y = validation["SalePrice"].values
# print(y_hat[:5])
# print(y[:5])
# mse = mean_squared_error(y.reshape(-1, 1), y_hat)
# msle = mean_squared_log_error (y.reshape(-1, 1), y_hat)
# rmsle = np.sqrt (msle)
# print(rmsle)

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
reg_yr = LinearRegression()
reg_yr.fit(train["YearBuilt"].values.reshape(-1, 1), train["SalePrice"].values.reshape(-1, 1))
y_hat = reg_yr.predict(validation["YearBuilt"].values.reshape(-1, 1))
y = validation["SalePrice"].values
print(y_hat[:5])
print(y[:5])
mse = mean_squared_error(y.reshape(-1, 1), y_hat)
msle = mean_squared_log_error (y.reshape(-1, 1), y_hat)
rmsle = np.sqrt (msle)
print(rmsle)

In [0]:
plt.scatter(labeled["YearBuilt"], labeled["SalePrice"])
plt.show()

In [0]:
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(degree=2)
reg_yr_poly = LinearRegression()
reg_yr_poly.fit(poly.fit_transform(train["YearBuilt"].values.reshape(-1, 1)), train["SalePrice"].values.reshape(-1, 1))
y_hat = reg_yr_poly.predict(poly.fit_transform(validation["YearBuilt"].values.reshape(-1, 1)))
y = validation["SalePrice"].values
print(y_hat[:5])
print(y[:5])
mse = mean_squared_error(y.reshape(-1, 1), y_hat)
msle = mean_squared_log_error (y.reshape(-1, 1), y_hat)
rmsle = np.sqrt (msle)
print(rmsle)

In [0]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt

labeled = train

train1, validation1 = train_test_split(labeled, test_size=0.3, random_state=123)

X_train = train.loc[:, "YearBuilt"].values.reshape(-1, 1)
y_train = train.loc[:, "SalePrice"].values.reshape(-1, 1)
X_arr = np.linspace(labeled["YearBuilt"].min(), labeled["YearBuilt"].max()).reshape(-1, 1)
y_poly_arr = dict()
for d in range(1, 4):
  X_train_poly = PolynomialFeatures(d).fit_transform(X_train)
  reg_poly = LinearRegression()
  reg_poly.fit(X_train_poly, y_train)
  X_arr_poly = PolynomialFeatures(d).fit_transform(X_arr)
  y_arr = reg_poly.predict(X_arr_poly)
  y_poly_arr[d] = y_arr

In [0]:
plt.scatter(labeled["YearBuilt"], labeled["SalePrice"], s=7)
plt.xlabel("Year Built")
plt.ylabel("Sale Price")
plt.plot(X_arr, y_poly_arr[1], color = "r", label = "Degree=1")
plt.plot(X_arr, y_poly_arr[2], color = "g", label = "Degree=2")
plt.plot(X_arr, y_poly_arr[3], color = "y", label = "Degree=3")
plt.legend(loc="upper left")
plt.show()

In [0]:
def get_mse_by_degrees(labeled, degrees = range(1, 11)):
  train, validation = train_test_split(labeled, test_size=0.3) #random_state was removed, meaning that the 25:75 datase is floating
  X_train = train.loc[:, "YearBuilt"].values.reshape(-1, 1)
  y_train = train.loc[:, "SalePrice"].values.reshape(-1, 1)
  X_validation = validation.loc[:, "YearBuilt"].values.reshape(-1, 1)
  y_validation = validation.loc[:, "SalePrice"].values.reshape(-1, 1)
  mse_train_arr = np.zeros(len(degrees))
  mse_valid_arr = np.zeros(len(degrees))
  for d in degrees:
    X_train_poly = PolynomialFeatures(d).fit_transform(X_train)
    reg_poly = LinearRegression()
    reg_poly.fit(X_train_poly, y_train)
    X_validation_poly = PolynomialFeatures(d).fit_transform(X_validation)
    y_hat = reg_poly.predict(X_validation_poly)
    mse_valid = mean_squared_error(y_validation, y_hat)
    y_hat = reg_poly.predict(X_train_poly)
    mse_train = mean_squared_error(y_train, y_hat)
    mse_valid_arr[d-1] = mse_valid
    mse_train_arr[d-1] = mse_train
  best_degree = mse_valid_arr.argmin() + 1
  return mse_valid_arr, mse_train_arr, best_degree

In [0]:
degrees = range(1, 11) 
mse_valid_arr, mse_train_arr, best_degree = get_mse_by_degrees(labeled, degrees) 
#labled data was randomly chosen in each run, so the best degree varies based on different data was given. 
#This problem can be solved by cross-validation

In [0]:
print("Best Degree: {}".format(best_degree))
plt.plot(degrees, mse_valid_arr, color="r", label="Validation")
plt.plot(degrees, mse_train_arr, color="g", label="Train")
plt.legend()
plt.show()

In [0]:
X_train = train.loc[:, ["YearBuilt", "GrLivArea", "GarageArea"]].values
PolynomialFeatures(2).fit_transform(X_train).shape

In [0]:
def get_mse_by_degrees(labeled, degrees = range(1, 11)):
  train, validation = train_test_split(labeled, test_size=0.3)
  X_train = train.loc[:, ["YearBuilt", "GrLivArea", "GarageArea"]].values
  y_train = train.loc[:, "SalePrice"].values.reshape(-1, 1)
  X_validation = validation.loc[:, ["YearBuilt", "GrLivArea", "GarageArea"]].values
  y_validation = validation.loc[:, "SalePrice"].values.reshape(-1, 1)
  mse_train_arr = np.zeros(len(degrees))
  mse_valid_arr = np.zeros(len(degrees))
  for d in degrees:
    X_train_poly = PolynomialFeatures(d).fit_transform(X_train)
    reg_poly = LinearRegression()
    reg_poly.fit(X_train_poly, y_train)
    X_validation_poly = PolynomialFeatures(d).fit_transform(X_validation)
    y_hat = reg_poly.predict(X_validation_poly)
    mse_valid = mean_squared_error(y_validation, y_hat)
    y_hat = reg_poly.predict(X_train_poly)
    mse_train = mean_squared_error(y_train, y_hat)
    mse_valid_arr[d-1] = mse_valid
    mse_train_arr[d-1] = mse_train
  best_degree = mse_valid_arr.argmin() + 1
  return mse_valid_arr, mse_train_arr, best_degree
#multiple variables in one regression, meaning that the situation of multicollinearity occurs

In [0]:
degrees = range(1, 11)
mse_valid_arr, mse_train_arr, best_degree = get_mse_by_degrees(labeled, degrees)
plt.plot(degrees, mse_valid_arr, color="r", label="Validation")
plt.plot(degrees, mse_train_arr, color="g", label="Train")
plt.legend()
plt.show()

In [0]:
from sklearn.linear_model import Ridge #Ridge regression is one of the ways to solve multicollinearity
from sklearn.model_selection import GridSearchCV #GridSearchCV enables cross validation
from scipy.special import boxcox, inv_boxcox
from google.colab import files


X_train = train.loc[:, ["YearBuilt", "GrLivArea", "GarageArea", "LotArea","TotalSF","OverallQual",\
                        "GarageCars","ExterQual","TotRmsAbvGrd","FullBath","KitchenQual"]].values
y_train = train.loc[:, "SalePriceSkewed"].values.reshape(-1, 1)
y_train_Origin = train.loc[:, "SalePrice"]

X_valid = validation.loc[:, ["YearBuilt", "GrLivArea", "GarageArea", "LotArea","TotalSF","OverallQual",\
                             "GarageCars","ExterQual","TotRmsAbvGrd","FullBath","KitchenQual"]].values
y_valid = validation.loc[:, "SalePriceSkewed"].values.reshape(-1, 1)
y_valid_Origin = validation.loc[:, "SalePrice"]


reg = Ridge()
parameters = {"alpha": [1, 10, 10**2, 10**3, 10**4, 10**5, 10**6]}
gridclassifier=GridSearchCV(reg, param_grid=parameters, cv=4, scoring="neg_mean_squared_log_error") #cross validation = 4 or k-fold
gridclassifier.fit(X_train, y_train)
y_hat_train = gridclassifier.predict(X_train)
y_hat_train = inv_boxcox(y_hat_train,0.15)
msle_train = mean_squared_log_error (y_train_Origin, y_hat_train)
rmsle_train = np.sqrt (msle_train)
print(rmsle_train)


y_hat_valid = gridclassifier.predict(X_valid)
y_hat_valid = inv_boxcox(y_hat_valid,0.15)
msle_valid = mean_squared_log_error (y_valid_Origin, y_hat_valid)
rmsle_valid = np.sqrt (msle_valid)
print(rmsle_valid)
validation["Predicted_SalePrice"] = y_hat_valid

validation.head()
export = validation.loc[:,['Id','Predicted_SalePrice']]
export.to_csv('submission.csv',index=False)
export.head()
#files.download("submission.csv")

In [0]:
gridclassifier.best_estimator_

In [0]:
gridclassifier.best_params_

In [0]:
gridclassifier.best_score_